//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeling
    {
        public string ClientFromFirstName { get; set; }
        public string ClientFromLastName { get; set; }
        public string Feeling1 { get; set; }
        public string ClientToFirstName { get; set; }
        public string ClientToLastName { get; set; }
        public int ClientFromId { get; set; }
        public int ClientToId { get; set; }
        public int FeelingTypeId { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
    }
}
