//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public string ReceptionName { get; set; }
        public System.DateTime ReceptionDate { get; set; }
        public string DishType { get; set; }
        public string DishName { get; set; }
        public int ReceptionId { get; set; }
        public int DishId { get; set; }
        public int DishTypeId { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string ModifiedBy { get; set; }
    }
}
